A,B,C,=map(float, input().split()) 
A= float(A)
B= float(B)
C= float(C)
print(f"TRIANGULO: {(A*C) / 2.00:.3f}")
pi=3.14159
print (f"CIRCULO: {pi*C*C:.3f}")
print(f"TRAPEZIO: {(A+B)* C/ 2.0:.3f}")
print(f"QUADRADO: { B*B:.3f}")
print(f"RETANGULO: { A*B:.3f}")
